### ISSUE TITLE
Compiler Issues w/ Dashboard

### ISSUE THREAD

**Issue by daltongilmore** [umkc-cs-451-2020-spring/Transaction-Trigger-Tracker#47]
Lots of errors come up when I try to compile from the dashboard directory. Get the error "cannot get /" on the webpage.

**Comment by alexasummers** [comment]
Make sure that the correct web page is being opened inside the app.component.html folder. Also make sure that all the needed modules are imported, and make sure the app.modules.ts is updated and saved.

**Comment by daltongilmore** [comment]
> Make sure that the correct web page is being opened inside the app.component.html folder. Also make sure that all the needed modules are imported, and make sure the app.modules.ts is updated and saved.

This worked! Thanks. The ts files weren't saved at the time
